### ISSUE TITLE
Ejemplos xml y json

### ISSUE THREAD

**Issue by daniel89fg** [Barnetik/tbai-php-lib#1]
Hola.

Estoy trabajando para implementar la librería con FacturaScripts pero necesitamos ver un ejemplo del xml y json para saber como debemos generarlo. En los Test vemos que hacen referencia a unos archivos en la caprta __filespero dichos archivos no están. ¿Pueden subirlos?. O mostrar un ejemplo de como montar dichos json y xml para avanzar un poco más.

Gracias.

**Comment by arraintxo** [comment]
Buenas @daniel89fg ,

he añadido la definición de las estructuras json necesarias para ser utilizadas con los métodos createFromJson en los siguientes archivos:
   * [Estructura Ticketbai](https://github.com/Barnetik/tbai-php-lib/blob/main/docs/ticketbai-json.md)   
   * [Estructura TicketbaiCancel](https://github.com/Barnetik/tbai-php-lib/blob/main/docs/ticketbai-cancel-json.md)

Como dices, existe un archivo de ejemplo en la carpeta de tests aunque supongo que no lo has encontrado porque debería hacer un poco de limpieza en esa estructura de directorios y tests:
  * [Ejemplo factura desde json](https://github.com/Barnetik/tbai-php-lib/blob/main/tests/Barnetik/Tbai/__files/tbai-sample.json)

Espero que con esto te valga para empezar ha hacer pruebas.
