### ISSUE TITLE
Dokumentazioa

### ISSUE THREAD

**Issue by asierblaz** [Barnetik/tbai-php-lib#12]
Kaixo dokumentazioa igoko duzue? edo adibideren bat, fakturak egiteko?

Eskerrikasko

**Comment by arraintxo** [comment]
Ziur adibide pare bat jarriko ditugula honetarako denbora apur bat ateratzen dugunean, bitartean test-en artean dagoen TicketBaiMother klasean fakturak zelan sortu ikusi dezakezu: https://github.com/Barnetik/tbai-php-lib/blob/main/tests/Barnetik/Tbai/Mother/TicketBaiMother.php

Hauek sinatu eta bidaltzeko egin beharrekoak ere edozein "Endpoint"eko testetan ikusi dezakezu:
-  Araba: https://github.com/Barnetik/tbai-php-lib/blob/main/tests/Barnetik/Tbai/Api/Araba/EndpointTest.php
-  Bizkaia: https://github.com/Barnetik/tbai-php-lib/blob/main/tests/Barnetik/Tbai/Api/Bizkaia/EndpointTest.php
-  Gipuzkoa: https://github.com/Barnetik/tbai-php-lib/blob/main/tests/Barnetik/Tbai/Api/Gipuzkoa/EndpointTest.php

**Comment by asierblaz** [comment]
bale ba, eskerrikasko!

**Comment by ortegafernando** [comment]
Kaixo, norbaitek eman al dezake bere "hello world"? Thanks

**Comment by arraintxo** [comment]
Egun on @ortegafernando 

Hemen helloworld sinple bat. "tbai-sample.json" fitxategia testen direktoriopean topatu dezakezu

```php
use Barnetik\Tbai\Api\Gipuzkoa\Endpoint as GipuzkoaEndpoint;
use Barnetik\Tbai\Fingerprint\Vendor;
use Barnetik\Tbai\PrivateKey;
use Barnetik\Tbai\TicketBai;

$license = 'DEV_LICENSE';
$developerCif = 'CIF';
$appName = 'APP NAME';
$version = '1.0';

$certificatePath = '/path/to/certificate.p12';
$certificatePassword = 'myCertificatePassword';
$signedXml = './signed.xml';

$ticketbai = TicketBai::createFromJson(
    new Vendor($license, $developerCif, $appName, $version),
    json_decode(file_get_contents('tbai-sample.json'), true)
);

$ticketbai->sign(
    PrivateKey::p12($certificatePath),
    $certificatePassword,
    $signedXml
);

// new GipuzkoaEnpoint() for production server
$gipuzkoaEndpoint = new GipuzkoaEndpoint(true, true);
$result = $gipuzkoaEndpoint->submitInvoice(
    $ticketbai,
    PrivateKey::p12($certificatePath),
    $certificatePassword,
);

if ($result->isDelivered()) {
    var_dump('SUCCESS!');
} else {
    var_dump($result->errorDataRegistry());
}
```

**Comment by arraintxo** [comment]
README-an bertan gehitu dugu liburutegia erabiltzeko behar den informazio apurra.
