### ISSUE TITLE
VatDetail::toArray() bug

### ISSUE THREAD

**Issue by Txej** [Barnetik/tbai-php-lib#13]
Kaixo,

Sospecho de un posible bug en el metodo toArray() de la clase VatDetail en el fichero Barnetik\Tbai\Invoice\Breakdown\VatDetail.php linea 123:

    public function toArray(): array
    {
        return [
            'taxBase' => (string)$this->taxBase,
            'taxRate' => $this->taxRate ? (string)$this->taxRate : null,
            'taxQuota' => $this->taxRate ? (string)$this->taxRate : null, //ESTA ES LA LINEA EN CUESTION
            'equivalenceRate' => $this->equivalenceRate ? (string)$this->equivalenceRate : null,
            'equivalenceQuota' => $this->equivalenceQuota ? (string)$this->equivalenceQuota : null,
            'isEquivalenceOperation' => $this->isEquivalenceOperation ?? null,
        ];
    }

Eskerrik asko zuen lanagatik
Agur bat

**Comment by arraintxo** [comment]
Konpoduta. 
Eskerrik asko abisuagatik
