### ISSUE TITLE
Error 5007 - Cliente de la factura extranjero

### ISSUE THREAD

**Issue by daniel89fg** [Barnetik/tbai-php-lib#16]
Hola.

Tengo un problema que no sé como solucionar bien. Para FacturaScripts siempre creamos un json y trabajamos con el para luego mandar dicho array a generar el xml.

Este sería nuestro json de ejemplo:
`Array ( [territory] => 03 [subject] => Array ( [issuer] => Array ( [vatId] => 74003828V [name] => E-1813 ) [recipients] => Array ( [0] => Array ( [vatId] => MSU871403S [vatIdType] => 03 [name] => Alayn Chequebara [postalCode] => 00522 [address] => Puerto Principe, 33 [countryCode] => HR ) ) [issuedBy] => N ) [invoice] => Array ( [header] => Array ( [series] => T2 [invoiceNumber] => 5 [expeditionDate] => 07-11-2022 [expeditionTime] => 15:39:34 [simplifiedInvoice] => ) [data] => Array ( [description] => FAC2022T25 [details] => Array ( [0] => Array ( [description] => Producto 1 [unitPrice] => 10 [quantity] => 1 [discount] => 0 [totalAmount] => 12.1 ) ) [total] => 12.1 [vatRegimes] => Array ( [0] => 01 ) [supportedRetention] => ) [breakdown] => Array ( [nationalSubjectNotExemptBreakdownItems] => Array ( [0] => Array ( [type] => S1 [vatDetails] => Array ( [0] => Array ( [taxBase] => 10 [taxRate] => 21 [taxQuota] => 2.1 [equivalenceRate] => [equivalenceQuota] => [isEquivalenceOperation] => ) ) ) ) ) ) [fingerprint] => Array ( [previousInvoice] => Array ( [invoiceNumber] => 4 [sentDate] => 07-11-2022 [signature] => SRN+2AL5V0V+mY8xGklYgT3EkPTjk1vgt5O826q9XOFgy38l5dL3a94MwGWTQECZrZQft/3BtSfyDcv97nPv8MXU6kx4gNUUke+l [serie] => T2 ) ) )`

Al mandar una factura con un cliente extranjero, osea con su pasaporte en vez de DNI, hacienda marca un warning diciendo: error 5007 - el campo DesgloseFactura solo se puede utilizar cuando el Destinatario de una factura es un Español.

Pero no sabemos que tenemos que hacer para quitar en el json lo necesario para que el campo DesgloseFactura salga correcto.

Este es nuestro xml generado de ejemplo:
`<?xml version="1.0" encoding="utf-8"?>
<T:TicketBai xmlns:T="urn:ticketbai:emision"><Cabecera><IDVersionTBAI>1.2</IDVersionTBAI></Cabecera><Sujetos><Emisor><NIF>74003828V</NIF><ApellidosNombreRazonSocial>E-1813</ApellidosNombreRazonSocial></Emisor><Destinatarios><IDDestinatario><IDOtro><CodigoPais>HR</CodigoPais><IDType>03</IDType><ID>MSU871403S</ID></IDOtro><ApellidosNombreRazonSocial>Alayn Chequebara</ApellidosNombreRazonSocial><CodigoPostal>00522</CodigoPostal><Direccion>Puerto Principe, 33</Direccion></IDDestinatario></Destinatarios><VariosDestinatarios>N</VariosDestinatarios><EmitidaPorTercerosODestinatario>N</EmitidaPorTercerosODestinatario></Sujetos><Factura><CabeceraFactura><SerieFactura>T2</SerieFactura><NumFactura>5</NumFactura><FechaExpedicionFactura>07-11-2022</FechaExpedicionFactura><HoraExpedicionFactura>15:39:34</HoraExpedicionFactura><FacturaSimplificada>N</FacturaSimplificada></CabeceraFactura><DatosFactura><DescripcionFactura>FAC2022T25</DescripcionFactura><DetallesFactura><IDDetalleFactura><DescripcionDetalle>Producto 1</DescripcionDetalle><Cantidad>1</Cantidad><ImporteUnitario>10</ImporteUnitario><Descuento>0</Descuento><ImporteTotal>12.1</ImporteTotal></IDDetalleFactura></DetallesFactura><ImporteTotalFactura>12.1</ImporteTotalFactura><Claves><IDClave><ClaveRegimenIvaOpTrascendencia>01</ClaveRegimenIvaOpTrascendencia></IDClave></Claves></DatosFactura><TipoDesglose><DesgloseFactura><Sujeta><NoExenta><DetalleNoExenta><TipoNoExenta>S1</TipoNoExenta><DesgloseIVA><DetalleIVA><BaseImponible>10</BaseImponible><TipoImpositivo>21</TipoImpositivo><CuotaImpuesto>2.1</CuotaImpuesto><OperacionEnRecargoDeEquivalenciaORegimenSimplificado>N</OperacionEnRecargoDeEquivalenciaORegimenSimplificado></DetalleIVA></DesgloseIVA></DetalleNoExenta></NoExenta></Sujeta></DesgloseFactura></TipoDesglose></Factura><HuellaTBAI><EncadenamientoFacturaAnterior><SerieFacturaAnterior>T2</SerieFacturaAnterior><NumFacturaAnterior>4</NumFacturaAnterior><FechaExpedicionFacturaAnterior>07-11-2022</FechaExpedicionFacturaAnterior><SignatureValueFirmaFacturaAnterior>SRN+2AL5V0V+mY8xGklYgT3EkPTjk1vgt5O826q9XOFgy38l5dL3a94MwGWTQECZrZQft/3BtSfyDcv97nPv8MXU6kx4gNUUke+l</SignatureValueFirmaFacturaAnterior></EncadenamientoFacturaAnterior><Software><LicenciaTBAI>TBAIGIPRE00000000804</LicenciaTBAI><EntidadDesarrolladora><NIF>74003828V</NIF></EntidadDesarrolladora><Nombre>FacturaScripts</Nombre><Version>1.0</Version></Software></HuellaTBAI><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></ds:CanonicalizationMethod>
    <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"></ds:SignatureMethod>
  <ds:Reference URI="#signed-properties" Type="http://uri.etsi.org/01903#SignedProperties"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod><ds:DigestValue>UXHht0DO7oIXHc45V+T+DmNT+Y1J6Edq12XbsPdJR4M=</ds:DigestValue></ds:Reference><ds:Reference URI="" Id="xmldsig-db833212-4357-98b6-f18b-b05176741a1d"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod><ds:DigestValue>4prtnL4M96mVbfiPxbcAgIMdJJ+xMs4GXZBaAzvAY/A=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>nuveemLBHE6M7ZUhb/zTgtEbCAd25PFaOFewo4U3atkBve7MNSRvFVET0OI1dFTHArwTKn5ZNkSeIvXxTYFK5i46N7ujjkJ3UvJ27foiko461CziGcfyHP9aL+TIWC+ixpDrO0RwssQ+Y2H0YXX8phWfAWwBuvrUCjClm1WEGHV6Po020Jf/HV82EFAGIUoMRDlf0eUEMwGku2NRDNy2e5QWpTZAnzeJobrGbpQACxBhH3RaaupQFXH9j3ZEwH0hwvoQ86W6DVm1gHeTxzOmO7qKmgqkzURYn3MNSVormVq5bnQDVP4LvdLRCXM+u3EjtGpyAehNt/q+L5QcUSiT/g==</ds:SignatureValue>
<ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIJmjCCB4KgAwIBAgICG3QwDQYJKoZIhvcNAQELBQAwgZcxCzAJBgNVBAYTAkVTMRQwEgYDVQQKDAtJWkVOUEUgUy5BLjE6MDgGA1UECwwxTlpaIFppdXJ0YWdpcmkgcHVibGlrb2EgLSBDZXJ0aWZpY2FkbyBwdWJsaWNvIFNDSTE2MDQGA1UEAwwtQ0EgZGUgQ2l1ZGFkYW5vcyB5IEVudGlkYWRlcyAoNCkgLSBERVNBUlJPTExPMB4XDTIxMDMxNTEwMDExOFoXDTI1MDMxNTEwMDExOFowga0xCzAJBgNVBAYTAkVTMTgwNgYDVQQLDC9IZXJyaXRhciB6aXVydGFnaXJpYSAtIENlcnRpZmljYWRvIGRlIGNpdWRhZGFubzEiMCAGA1UEAwwZTlVFVk9DSVVEIEZJQ1RJQ0lPIEFDVElWTzEYMBYGA1UEBAwPRklDVElDSU8gQUNUSVZPMRIwEAYDVQQqDAlOVUVWT0NJVUQxEjAQBgNVBAUTCTk5OTk5OTcyQzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOo/rdu+7QTGGnrK2VGWGOwrVzC7Ozo5RulBLJceVxWcmUxc3E6wYdG1MJWZA6v/vUe5F3c4Nep6UgSI1BjYrbSYNHHsSxxn15NMNghnC+z857G7pBP2+W/xfcX0OOfaN7luhnyLZy8tVmEnOudIEnLaKELgRlG28gN1cf8BiBLciQx2Q+OYftVKIM13vVt6lErn+4gRoq4KrGH1oMqBs6sHLfm8bWRBArBEvJde74kLxY9v/iACKG4XsE6aDuVBkGOSFCEaf154HNa3nFRekNM9Xct7DvJoaoyGx2077sqnbXM1vOZ9GpcRLGq/JXrHYvssEBDxLqX0b4CyurvcAscCAwEAAaOCBNYwggTSMIHHBgNVHRIEgb8wgbyGFWh0dHA6Ly93d3cuaXplbnBlLmNvbYEPaW5mb0BpemVucGUuY29tpIGRMIGOMUcwRQYDVQQKDD5JWkVOUEUgUy5BLiAtIENJRiBBMDEzMzcyNjAtUk1lcmMuVml0b3JpYS1HYXN0ZWl6IFQxMDU1IEY2MiBTODFDMEEGA1UECQw6QXZkYSBkZWwgTWVkaXRlcnJhbmVvIEV0b3JiaWRlYSAxNCAtIDAxMDEwIFZpdG9yaWEtR2FzdGVpejCBmAYDVR0RBIGQMIGNpIGKMIGHMSEwHwYJKwYBBAHzOQAHDBJjb250YWN0b0BlbWFpbC5jb20xGDAWBgkrBgEEAfM5AAQMCTk5OTk5OTcyQzEVMBMGCSsGAQQB8zkAAwwGQUNUSVZPMRcwFQYJKwYBBAHzOQACDAhGSUNUSUNJTzEYMBYGCSsGAQQB8zkAAQwJTlVFVk9DSVVEMA4GA1UdDwEB/wQEAwIF4DAfBgNVHSUEGDAWBggrBgEFBQcDAgYKKwYBBAGCNwoDDDAdBgNVHQ4EFgQU+kSy1bOCUx16/rZ41zuwCOktvrowHwYDVR0jBBgwFoAUb//9DfIMYw8mcV0a4G9lZGY4a5MwggEqBgNVHSAEggEhMIIBHTCCAQ4GCisGAQQB8zlmEgEwgf8wJQYIKwYBBQUHAgEWGWh0dHA6Ly93d3cuaXplbnBlLmV1cy9jcHMwgdUGCCsGAQUFBwICMIHIDIHFS29udHN1bHRhIHd3dy5pemVucGUuZXVzLWVuIGJhbGRpbnR6YWsgZXRhIGtvbmRpemlvYWsgeml1cnRhZ2lyaWFuIGZpZGF0dSBlZG8gZXJhYmlsaSBhdXJyZXRpayAtIENvbnN1bHRlIGVuIHd3dy5pemVucGUuZXVzIGxvcyB0w6lybWlub3MgeSBjb25kaWNpb25lcyBhbnRlcyBkZSB1dGlsaXphciBvIGNvbmZpYXIgZW4gZWwgY2VydGlmaWNhZG8wCQYHBACL7EABAjCBogYIKwYBBQUHAQEEgZUwgZIwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwZGVzLml6ZW5wZS5jb20waQYIKwYBBQUHMAKGXWh0dHA6Ly93d3cuaXplbnBlLmV1cy9jb250ZW5pZG9zL2luZm9ybWFjaW9uL2Nhc19pemVucGUvZXNfY2FzL2FkanVudG9zL0NDRUVSX2NlcnRfc2hhMjU2LmNydDAoBgNVHQkEITAfMB0GCCsGAQUFBwkBMREYDzIwMDAwMzE1MDAwMDAwWjCBxAYIKwYBBQUHAQMEgbcwgbQwCAYGBACORgEBMAgGBgQAjkYBBDALBgYEAI5GAQMCAQ8wfAYGBACORgEFMHIwJBYeaHR0cHM6Ly93d3cuaXplbnBlLmV1cy9wZHMvZW4vEwJlbjAkFh5odHRwczovL3d3dy5pemVucGUuZXVzL3Bkcy9ldS8TAmV1MCQWHmh0dHBzOi8vd3d3Lml6ZW5wZS5ldXMvcGRzL2VzLxMCZXMwEwYGBACORgEGMAkGBwQAjkYBBgEwNgYDVR0fBC8wLTAroCmgJ4YlaHR0cDovL2NybGRlcy5pemVucGUuY29tL2NnaS1iaW4vY3JsMjANBgkqhkiG9w0BAQsFAAOCAgEAcIyECVysDiBWRTJtfU+VqlAxHhAPouaY+tq7TL78MT7z84v8n+dJMQH8TTZFl6+Gyhlxw4mUULr5qmuOCPWcAXU6NQFu/j0oQz6zGOmHq5i5X5OnmtFNd91Md1Rz/y09Q4F1/8zESMG3Xc9wdoAWaot8z4+gGKVGUFkihWOk6VTDEBwC7QQKPhgZkpRHkrnK0bhSPr3YGtcNEr4/uNe8sVlEWtHN3N0JsM+9bloBZj/HOEwPq9sarh9iUR3Mzmg5lGGJnKWWJ0nqC9A0Ix8z0yfenLRQn6v3H/AsoLAC0kLo6GkiV3W1AMDMGq2zqaSEcCwshVPpp5z4jUvVPasAfgLUzS8L3x3ek8h6UYQ+y1eITp5KnjoG+Ks7AvkRTwMBfUFrCQeO7w091slC0ksgEtMyeLuIOqUf+DHD76I+hGuJv9PmjrPey8O2b0szo9//rW5M849SVi4gGhoJw7drkHIh24l0+8rTgv0foVl1MnGfEJTeU/ovHtymXBkUnd9ugC0Lci4rCWBy+vptNavF4BLW6onjtM0sa/i/51HL3BnyWXgWI/C/RbPu8/ljqfjPQi9m4mv/tO3YAGyqiQv8C1Uy7+HcSgMLZnqZq0LWYKibJ//VcIDkG1uv0qO8Pg6abJ3YcPuy3Z7+0LV/naymQzEG6p7QtWOAHrK/YOnKu84=</ds:X509Certificate></ds:X509Data></ds:KeyInfo><ds:Object><xa:QualifyingProperties xmlns:xa="http://uri.etsi.org/01903/v1.3.2#" Target="#"><xa:SignedProperties Id="signed-properties"><xa:SignedSignatureProperties><xa:SigningTime>2022-11-07T15:39:42+01:00</xa:SigningTime><xa:SigningCertificateV2><xa:Cert><xa:CertDigest><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod><ds:DigestValue>4Ho+z1h9r3MhM5bCF9Blc1bvFPXnS1hpNqjOI4f77MQ=</ds:DigestValue></xa:CertDigest></xa:Cert></xa:SigningCertificateV2><xa:SignaturePolicyIdentifier><xa:SignaturePolicyId><xa:SigPolicyId><xa:Identifier>https://www.gipuzkoa.eus/ticketbai/sinadura</xa:Identifier></xa:SigPolicyId><xa:SigPolicyHash><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod><ds:DigestValue>vSe1CH7eAFVkGN0X2Y7Nl9XGUoBnziDA5BGUSsyt8mg=</ds:DigestValue></xa:SigPolicyHash><xa:SigPolicyQualifiers><xa:SigPolicyQualifier>https://www.gipuzkoa.eus/ticketbai/sinadura</xa:SigPolicyQualifier></xa:SigPolicyQualifiers></xa:SignaturePolicyId></xa:SignaturePolicyIdentifier></xa:SignedSignatureProperties><xa:SignedDataObjectProperties><xa:DataObjectFormat ObjectReference="#xmldsig-db833212-4357-98b6-f18b-b05176741a1d"><xa:Description>FAC2022T25-signed-7k4PL3.xml</xa:Description><xa:MimeType>text/xml</xa:MimeType></xa:DataObjectFormat></xa:SignedDataObjectProperties></xa:SignedProperties></xa:QualifyingProperties></ds:Object></ds:Signature></T:TicketBai>
`

**Comment by arraintxo** [comment]
Supongo que tendremos que modificar el código para que el desglose factura no se genere cuándo este está vacío, puedes pegar directamente el JSON por aquí para hacer las pruebas necesarias?

**Comment by daniel89fg** [comment]
El json está pegado arriba del hilo.

**Comment by arraintxo** [comment]
Buenas @daniel89fg ,

Me refería en un formato procesable para PHP.

En vez de un var_dump, un var_export, o un echo del json_encode me valdrían.

**Comment by daniel89fg** [comment]
Con var_export
`array ( 'territory' => '03', 'subject' => array ( 'issuer' => array ( 'vatId' => '74003828V', 'name' => 'E-1813', ), 'recipients' => array ( 0 => array ( 'vatId' => 'MSU871403S', 'vatIdType' => '03', 'name' => 'Alayn Chequebara', 'postalCode' => '00522', 'address' => 'Puerto Principe, 33', 'countryCode' => 'HR', ), ), 'issuedBy' => 'N', ), 'invoice' => array ( 'header' => array ( 'series' => 'A', 'invoiceNumber' => '1', 'expeditionDate' => '08-11-2022', 'expeditionTime' => '12:44:10', 'simplifiedInvoice' => false, ), 'data' => array ( 'description' => 'FAC2022A1', 'details' => array ( 0 => array ( 'description' => 'Producto 1', 'unitPrice' => 10.0, 'quantity' => 1.0, 'discount' => 0.0, 'totalAmount' => 12.1, ), ), 'total' => 12.1, 'vatRegimes' => array ( 0 => '01', ), 'supportedRetention' => NULL, ), 'breakdown' => array ( 'nationalSubjectNotExemptBreakdownItems' => array ( 0 => array ( 'type' => 'S1', 'vatDetails' => array ( 0 => array ( 'taxBase' => 10.0, 'taxRate' => 21.0, 'taxQuota' => 2.1, 'equivalenceRate' => NULL, 'equivalenceQuota' => NULL, 'isEquivalenceOperation' => false, ), ), ), ), ), ), )`

**Comment by arraintxo** [comment]
Buenas @daniel89fg, 

había un error al crear las facturas con destinatario extranjero mediante JSON. Creo que ya estaría solucionado.

En el caso del json/array que envías como ejemplo te hará falta cambiar "nationalSubjectNotExemptBreakdownItems" por "foreignServiceSubjectNotExemptBreakdownItems" si es un _Desglose a nivel de prestación de servicios_ o por "foreignDeliverySubjectNotExemptBreakdownItems" en caso de ser un  _Desglose a nivel de entrega de bienes_

Gracias por reportar el error.

Un saludo
