### ISSUE TITLE
Error al firmar con NIF que empiezan por 0

### ISSUE THREAD

**Issue by elurk** [Barnetik/tbai-php-lib#17]
Al hacer un envío con ticketbai con un DNI que empieza por 0 da el error Wrong VatId provided.

**Comment by arraintxo** [comment]
Puedes pasarme un ejemplo? he probado con un par de ellos y no me da ningún error.

Supongo que si solo te ha pasado con los que empiezan por 0 ya lo has tenido en cuenta, pero el DNI debe ir sin guiones ni espacios. (pe: 12345678Z)

En caso de tener 0's al principio, los ceros también tienen que estar presentes en el string. (pe: "01234567S").
