### ISSUE TITLE
Bugs en funciones toArray/createFromJson

### ISSUE THREAD

**Issue by Txej** [Barnetik/tbai-php-lib#19]
Kaixo,

en el metodo toArray de la clase TicketBai.php es necesario añadir al array devuelto el resgistro 'self_employed' con el valor definido

Por otro lado, en el metodo toArray de la clase Collection.php se exportan los valores insertandolos en un array con la clave 'details'. Sin embargo, en el metodo createFromJson de la misma clase Collection.php, se busca la clave 'incomeTaxDetails'. Entiendo que ambas claves deberian coincidir para que todo funcione.

Eskerrik asko zuen lanagatik
Agur bat

**Comment by Txej** [comment]
Sucede algo parecido con la exportacion en TicketBai.php::toArray de batuzIncomeTaxes ya que se exporta un array vacio cuando no hay valor, pero en el metodo createFromJson, para verificar si debe cargarse, se compara contra valor vacio (es decir ''), en lugar de contra array vacio

**Comment by arraintxo** [comment]
Kaixo @Txej,
barkatu iragandako denboragatik.

- Se han corregido las inconsistencias que comentabas en esta incidencia. En principio no afectaba al funcionamiento de la librería, siempre y cuando el json utilizado para crear una factura no estuviese creado también con la propia librería, pero es verdad que podía ser confuso el que no se exportasen esas claves correctamente.
- En el caso de batuzIncomeTaxes ahora se comprueba que lo introducido no sea un array vacio.
- Hemos aprovechado también para corregir la utilización de "self_employed" en su formato "snake_case" para cambiarlo por "camelCase" que es como se utilizan todas las demás claves. Por ahora se permitirá el uso de ambos pero se emite un E_USER_DEPRECATED para que dejéis de "self_employed".

Eskerrik asko zure ekarpenengatik
