### ISSUE TITLE
unable to load client cert: -8018 (SEC_ERROR_UNKNOWN_PKCS11_ERROR)

### ISSUE THREAD

**Issue by FacturaOne** [Barnetik/tbai-php-lib#2]
Hola, estoy probando la librería y funciona muy bien 🚀🚀🚀 muchas gracias, gran trabajo.

Pero he encontrado que si el CURL esta compilado en NSS no funciona, solo funciona con OpenSSL.
Para resolver el problema temporalmente y poderlo usar dentro de un entorno de CURL con NSS, he convertido el certificado "PertsonaFisikoa_PersonaFisica.p12" en: .....     file.crt.pem       file.key.pem

CMD Para convertir:
openssl pkcs12 -in PertsonaFisikoa_PersonaFisica.p12 -out file.key.pem -nocerts -nodes
openssl pkcs12 -in PertsonaFisikoa_PersonaFisica.p12 -out file.crt.pem -clcerts -nokeys

Modificación de AbstractTerritory.php ... la function .... getOptArray:
    CURLOPT_SSLCERT			=> './__files/file.crt.pem',
    CURLOPT_SSLKEY			=> './__files/file.key.pem',
    CURLOPT_SSLCERTPASSWD       => $password,
    CURLOPT_SSLKEYPASSWD         => $password

Entonces me deja enviarlo bien, y lo veo subido (con el enlace), pero me devuelve el siguinte error, en la respuesta del curl:
echo "Jasotako errore printzipala: " . $response->mainErrorMessage() . "\n";
-> Sinatutako fitxategia: signed-C1qyNr.xml Jasotako errore printzipala: {"codigo":"100"} 

Pero en la respuesta TicketBaiResponse parece que esta todo correcto:
<ns2:TicketBaiResponse xmlns:ns2="urn:ticketbai:emision">
    <Salida>
        <IdentificadorTBAI>TBAI-38815415V-240322-PYnDGESlD0e1t-184</IdentificadorTBAI>
        <FechaRecepcion>24-03-2022 14:29:11</FechaRecepcion>
        <Estado>00</Estado>
        <Descripcion>Recibido - ALTA PREP</Descripcion>
        <Azalpena>Jasota - ALTA PREP</Azalpena>
        <CSV>TBAI34f748a4-170c-4d50-9d0a-3f764477cbb0</CSV>
    </Salida>
</ns2:TicketBaiResponse>

**Comment by arraintxo** [comment]
Buenas @FacturaOne ,

he cambiado el código para permitir el uso de claves en formato PEM. Ahora en los lugares donde antes se pasaba una ruta al fichero .p12, debe enviarse un objeto de la clase \Barnetik\Tbai\PrivateKey

```php
        $privateKey = PrivateKey::pem($certFilePath, $keyFilePath);

        $ticketbai->sign($privateKey, $certPassword, $signedFilename);
        $endpoint = new Endpoint();
        $response = $endpoint->submitInvoice($ticketbai, $privateKey, $certPassword);

```

Respecto al codigo 100 no tengo claro a que tipo de error se refiere, en principio aunque los formatos de las claves sean distintas, el resultado debería ser el mismo, de hecho internamente en la firma del documento siempre se utiliza el formato PEM.

**Comment by FacturaOne** [comment]
Hola @arraintxo, gracias por tu rapida respuesta
acabo de actualizar a la version con PrivateKey::pem y funciona correcto :)

Por otro lado lo que te comentaba, te lo he puesto en esta imagen, ... 
si te fijas en la parte del codigo ... if(!$response->isCorrect()) ... da como resultado que es incorrecto y muestra ese resultado que te agrego a la derecha arriba, y en ese resultado la linea "Jasotako errore printzipala:" da como error {"codigo":"100"}

Por otro lado el TicketBaiResponse que te pongo abajo izquierda veo que llega sin errores, e incluso entro a la url que me ha generado y me da ok...

![Captura](https://user-images.githubusercontent.com/65960142/159966791-460b9e0d-97ab-487b-9b31-c82af5a9b23b.JPG)

**Comment by arraintxo** [comment]
Supongo que el error depende de la versión de curl que se esté utilizando y tiene que ver con que se envía la cabecera [Expect: 100-continue](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect) al servidor antes de hacer el POST.

He cambiado las peticiones para enviar vacío el "Expect:" y así evitar que se devuelva el código 100 en la respuesta. No sé si funcionará porque no sé como reproducir el problema en mi sistema.

También he cambiado la forma en la que se recupera el "HTTP status", por lo que si te funciona estaría bien que probases si sigue funcionando eliminando la línea 20 del [endpoint de Gipuzkoa](https://github.com/Barnetik/tbai-php-lib/blob/93d793ec76fde28fa6453c27b821a5e1243f475d/src/Barnetik/Tbai/Api/Gipuzkoa/Endpoint.php#L20) (Eliminar la cabecera "Expect: ").

**Comment by FacturaOne** [comment]
Acabo de probarlo y funciona correctamente, no llega con codigo error 100 :)
Por otro lado he probado de eliminar la linea 20 "expect:" y entonces no funciona.

Ayer con la ultima actualización vi que funcionaba en php 7, ... pero hoy ha dejado de ir dando este error:
Uncaught TypeError: Argument 2 passed to Barnetik\Tbai\Api\AbstractTerritory::parseCurlResponse() must be an instance of CurlHandle, resource given, called in /src/Barnetik/Tbai/Api/AbstractTerritory.php on line 54

**Comment by arraintxo** [comment]
Ya debería funcionar de nuevo con php7.4

**Comment by FacturaOne** [comment]
> Ya debería funcionar de nuevo con php7.4

Funciona perfecto 🚀🚀🚀

Por cierto, una cosilla, podríais hacer un ejemplo de casos del uso para añadir productos como el ejemplo de TicketBaiMother.php ... ($data->addDetail(new Detail('Artículo 1 Ejemplo)

Y otra cosilla, se tenia que enviar tambien algun hash encadenado o numero de factura anterior?  lo tenéis previsto por algún lado? mersi :)

**Comment by arraintxo** [comment]
Buenas @FacturaOne ,

¿tienes alguna duda específica al respecto de como poblar los detalles de los productos? En principio puedes usar la manera en la que se generan en el TicketBaiMother.

Por ahora no tenemos como tarea prioritaria documentar demasiado la librería con casos de uso y ejemplos porque todavía puede cambiar algo la interfaz. Aunque tampoco descarto el añadir un par de ejemplos en el README si saco algo de tiempo para ello.

De todos modos, échale un vistazo a la generación de facturas mediante JSON, porque yo creo que a día de hoy es la manera más sencilla de poblar las facturas.

Respecto al encadenamiento de facturas este se debe añadir a la huella o Fingerprint de la factura. La clase utilizada para ello es PreviousInvoice. En la clase TicketBaiMother también hay un ejemplo comentado (por ahora), pero en principio funciona correctamente. 

Para concatenar la factura anterior habría que hacer algo así:

```php
        $vendor = new Vendor($license, $developer, $appName, $appVersion);
        $previousInvoice = new PreviousInvoice('0000002', new Date('25-03-2022'), '100-caracteres-del-signatureValue-del-fichero-anterior', 'TESTSERIE');
        new Fingerprint($vendor, $previousInvoice);
```
