### ISSUE TITLE
Bug generación códigos QR

### ISSUE THREAD

**Issue by Txej** [Barnetik/tbai-php-lib#20]
Kaixo,

La generación de códigos QR no funciona bien cuando aparecen los caracteres '+' ó '/' como parte del identificador ticketbai, por formar parte de los 13 primeros  caracteres de la firma

A la hora de generar la URL del codigo QR, estos caracteres deben ser codificados mediante urlencode, debiendo generarse el CRC asociado a la URL con esta modificacion aplicada, mientras que el CRC del propio identificador ticketbai debe mantenerse tal cual

La solucion pasa por modificar la funcion Qr.php::urlQuery() para hacer el encoding al identificador ticketbai antes de que se genere el QR
    private function urlQuery(): string
    {
        return sprintf(
            'id=%s&s=%s&nf=%s&i=%s',
            urlencode($this->ticketbaiIdentifier()),
            $this->ticketBai->series(),
            $this->ticketBai->invoiceNumber(),
            $this->ticketBai->totalAmount()
        );
    }

Eskerrik asko zuen lanagatik
Agur bat

**Comment by arraintxo** [comment]
Arratsalde on,

ya está solucionado. Raro que no lo hubiesemos detectado antes porque al ejecutar varios tests, el error podía reproducirse...

Por si acaso ahora se hace un rawurlencode de los cuatro parámetros, aunque es muy poco probable que cualquiera de los otros tres pudiese fallar.

Eskerrik asko!
