### ISSUE TITLE
Problemas al enviar a Vizcaya

### ISSUE THREAD

**Issue by NeoRazorX** [Barnetik/tbai-php-lib#23]
Hola, primero de todo daros las gracias por esta librería.

Estamos teniendo problemas con un cliente de Vizcaya. El endpoint de Vizcaya siempre nos responde con "Todos los registros incluidos en la petición son incorrectos". Y por mucho que revisemos la documentación, solo vemos que es un mensaje genérico que usan mucho, y no sabemos por dónde seguir.

¿Os habéis encontrado antes con este problema? Tenéis algún consejo para saber de dónde puede venir el problema, o alguna forma de saber más del problema.

Gracias y feliz año (hasta febrero se puede decir).

**Comment by arraintxo** [comment]
La verdad es que no nos ha ocurrido desde hace tiempo (cuando empezamos con la librería sí se dió el caso). 

Os recomiendo que os pongáis en contacto con ellos y les enviéis los siguientes datos. A ver si con eso os pueden dar más información.

* NIF
* Fecha/hora de la petición
* IP desde la que se realiza la petición
* El fichero XML enviado
* Cabeceras de la respuesta
* Cuerpo de la respuesta

Si estáis usando la librería y podéis facilitarnos de alguna manera los datos que usáis para generar la petición, podríamos repasarlo cuando tengamos un rato.

Feliz año a vosotros también!

**Comment by arraintxo** [comment]
Cerramos la incidencia, porque parece que no hay mucho más que podamos aportar por aquí.

Un saludo
