### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by pmediel** [Barnetik/tbai-php-lib#24]
He intentado generar unos tests en mi proyecto y como no consigo obtener respuesta, he instalado directamente el paquete como un proyecto para correr los tests y obtengo la misma respuesta al intentar enviar las facturas : 

Endpoint (Test\Barnetik\Tbai\Api\Araba\Endpoint)
 ✘ TicketBai is delivered
   ┐
   ├ Exception: No response from server
   │
   ╵ D:\webs\tbai\src\Barnetik\Tbai\Api\AbstractTerritory.php:84
   ╵ D:\webs\tbai\src\Barnetik\Tbai\Api\AbstractTerritory.php:67
   ╵ D:\webs\tbai\src\Barnetik\Tbai\Api\AbstractTerritory.php:48
   ╵ D:\webs\tbai\tests\Barnetik\Tbai\Api\Araba\EndpointTest.php:47
   ┴

**Comment by arraintxo** [comment]
Perdón por tardar en responder @pmediel,

has configurado correctamente el phpunit.xml con los datos necesarios?
Y solo te da problemas el endpoint de Araba o nos pasas el resultado de ese test como ejemplo?

**Comment by arraintxo** [comment]
Cerramos la incidencia por falta de datos
