### ISSUE TITLE
Falta atributo en FechaOperacion en Data.php

### ISSUE THREAD

**Issue by necobm** [Barnetik/tbai-php-lib#29]
Buenos días, 

He visto que el DTO Barnetik\Tbai\Invoice\Data.php no tiene una propiedad para almacenar la fecha de operación de la factura, ni hay forma de definir este dato en el método xml(), si bien este atributo no es requerido por TicketBai, es cierto que existen casos en que esta fecha difiere de la fecha de emisión de la factura y es necesario enviarla en el XML, quedando de esta forma:

```
<DatosFactura>
      <FechaOperacion>05-06-2023</FechaOperacion>
      <DescripcionFactura>Mi descripción</DescripcionFactura>
      <DetallesFactura>
        <IDDetalleFactura>
          <DescripcionDetalle>Servicios</DescripcionDetalle>
          <Cantidad>12</Cantidad>
          <ImporteUnitario>3456</ImporteUnitario>
          <Descuento>0</Descuento>
          <ImporteTotal>50181.12</ImporteTotal>
        </IDDetalleFactura>
      </DetallesFactura>
      <ImporteTotalFactura>50181.12</ImporteTotalFactura>
      <Claves>
        <IDClave>
          <ClaveRegimenIvaOpTrascendencia>01</ClaveRegimenIvaOpTrascendencia>
        </IDClave>
      </Claves>
    </DatosFactura>
``` 

En nuestro caso, lo hemos solucionado haciendo una herencia a vuestra clase Data e insertando dicho dato en el objeto DOMNode que devuelve la clase padre.

¿Aceptáis una PR para agregar esto en vuestra clase?

Saludos.

**Comment by necobm** [comment]
Buenas @arraintxo, pues intentaré crear el PR agregando ese campo y si lo veis oportuno lo podéis mergear, de momento solo ese hemos echado en falta pero realmente no tenemos todavía muchos casos de uso como para explotar todas las variantes de configuración del XML de las facturas, por eso no hemos echado en falta otros campos. Saludos.

**Comment by arraintxo** [comment]
He aceptado el PR después de añadir un par de tests e inicilaizar el operationDate a null para evitar errores.
