### ISSUE TITLE
CancelTicketbai fingerprint

### ISSUE THREAD

**Issue by goear** [Barnetik/tbai-php-lib#33]
Kaixo @arraintxo 

Tengo una duda, a la hora de crear un objeto TicketBaiCancel, veo que en el constructor lleva

Barnetik\Tbai\FingerPrint en lugar de Barnetik\Tbai\CancelInvoice\FingerPrint

Saludos!

**Comment by arraintxo** [comment]
Pues tienes razón. En principio no había problema mientras no se le añadiese un PreviousInvoice ya que este no es parte del esquema de anulación de facturas pero para prevenir errores los suyo es que se utilice el Fingerprint de Barnetik\Tbai\CancelInvoice\FingerPrint, por lo que lo he cambiado. 

Cambia algo la API y puede que rompa alguna implementación, pero el cambio es muy pequeño y puede prevenir futuros problemas.

Tendré que plantearme el empezar a crear versiones semánticas de la librería para evitar problemas a los usuarios...

Solucionado en: 
https://github.com/Barnetik/tbai-php-lib/commit/901da9c4ad15f0a3e51b82110bb51b47cbfdeb70
