### ISSUE TITLE
Error en Header\RectifiedInvoice.php

### ISSUE THREAD

**Issue by fjsampe** [Barnetik/tbai-php-lib#35]
En linea 41 
$invoiceNumber = $xpath->evaluate('string(SerieFactura)', $contextNode);
y debe indicar:
En linea $invoiceNumber = $xpath->evaluate('string(NumFactura)', $contextNode);

**Comment by arraintxo** [comment]
Solucionado. Muchas gracias por el aviso.

https://github.com/Barnetik/tbai-php-lib/commit/5853abd7980766072161d4cfa57e364730c9aa53
