### ISSUE TITLE
Comprobar estado de factura

### ISSUE THREAD

**Issue by treefy** [Barnetik/tbai-php-lib#37]
Aupa @arraintxo 

Me gustaría saber si hay algún endpoint (si conoces) para ver el estado de una factura, en ocasiones, al enviar la petición a alguna de las haciendas, no hemos recibido respuesta por el motivo que sea (posible error por nuestra parte en el servidor), y no registramos la respuesta pero esta queda registrada en hacienda y al intentar enviar una petición nos dice que ese numero de factura ya existe.

La duda es; Es posible realizar una petición para conocer el estado de una factura registrada?

Eskerrik asko!

**Comment by arraintxo** [comment]
Buenas @treefy en el caso de Bizkaia creo que debería ser posible a través de la API del LROE. Aunque creo que no puedes pedir el estado de una factura en concreto sino recorrer el listado de las facturas emitidas: https://www.batuz.eus/es/documentacion-tecnica

En el caso de Gipuzkoa puedes usar el servicio KONTSULTA: https://www.gipuzkoa.eus/es/web/ogasuna/ticketbai/documentacion-y-normativa

En Araba no creo que haya nada parecido por ahora: https://web.araba.eus/eu/ogasuna/ticketbai/dokumentazio-teknikoa

**Comment by treefy** [comment]
mila esker @arraintxo
