### ISSUE TITLE
New types of IVA

### ISSUE THREAD

**Issue by ortegafernando** [Barnetik/tbai-php-lib#39]
May be it is necessary to include as new IVA types:

17 Operación acogida a alguno de los regímenes previstos en el capítulo XI del Título IX (OSS e IOSS)
19 Operaciones de actividades incluidas en el Régimen Especial de Agricultura, Ganadería y Pesca (REAGYP)

And also in no subject types:

OT No sujeto por el artículo 7 de la Norma Foral de IVA. Otros supuestos de no sujeción
RL No sujeto por reglas de localización
VT No sujeto, operaciones realizadas por cuenta de terceros
IE No sujeto en el TAI por reglas de localización, pero repercute impuesto extranjero, IPSI/IGIC o IVA de otro estado miembro UE

Thanks

**Comment by arraintxo** [comment]
This changes were added to the new release.
Thank you for opening this issue.
