### ISSUE TITLE
Quizás una función útil

### ISSUE THREAD

**Issue by ortegafernando** [Barnetik/tbai-php-lib#40]
Hola, podríais añadir esta función a:

barnetik\ticketbai\src\Barnetik\Tbai\Api\Bizkaia\Response.php

(y otros response de otras provincias, claro)

```
    public function allHeaders(): array
    {
        return $this->headers;
    }
```

Lo estamos usando para "archivar" la respuesta completa. 

Gracias.

**Comment by arraintxo** [comment]
Nos ha parecido buena idea por lo que hemos añadido la función para los responses de todas las provincias.
La función se llama ```headers()```
