### ISSUE TITLE
Error envío TBAI BIZKAIA

### ISSUE THREAD

**Issue by fjsampe** [Barnetik/tbai-php-lib#42]
Buenas tardes.
Tras implementar con éxito el envío a la diputación foral de Araba y Gipuzkoa. Tengo el problema en los envíos a la diputación foral de Bizkaia. Tras incorporar los datos facilitados para modelo 240 que incorporo a issuer y nif me retorna el siguiente error "El presentador no est� identificado."
![Captura de pantalla -2024-07-10 17-37-41](https://github.com/Barnetik/tbai-php-lib/assets/18520482/06ff9815-7948-4afc-b69f-94cd8ee66cfa).
Creo que el funcionamiento es algo distinto en esta diputación foral, puede ser que se me esté pasando algo por alto.
Los datos de licencia que se envían son los indicados en la web de batuz.

[https://www.batuz.eus/fitxategiak/batuz/lroe/Batuz_LROE_Entorno_Pruebas_Empresas_Desarrolladoras_V1_0_1.pdf?hash=c4a0ec7e82442175cf1573f28218b011]

▪ Licencia TBAI: TBAIBI00000000PRUEBA
▪ NIF entidad desarrolladora: A99800005
▪ Nombre: SOFTWARE GARANTE TICKETBAI PRUEBA
▪ Versión: 1.0

**Comment by fjsampe** [comment]
El problema quedó solucionado. Para trabajar en modo pruebas se deben de utilizar cualquiera de los certificados publicados en la web BATUZ. [https://www.batuz.eus/fitxategiak/batuz/lroe/batuz_lroe_ziurtagiriak_kit_certificados_v1_0_2.7z](url)

**Comment by fjsampe** [comment]
Solucionado

**Comment by arraintxo** [comment]
Correcto, se deben usar los certificados publicados por Batuz y los datos de emisor provistos por la diputación.

Un saludo,
