### ISSUE TITLE
ERROR ENVÍO TBAI - BIZKAIA (B4_1000002)

### ISSUE THREAD

**Issue by fjsampe** [Barnetik/tbai-php-lib#43]
![image](https://github.com/user-attachments/assets/737bb127-ffc0-46cf-8107-a44c5c8f0281)

Al realizar el envío me devuelve este error. Aparece en la documentación de Batuz, pero no entiendo a que se puede referir el error.
![image](https://github.com/user-attachments/assets/63250c6b-49d1-4d7d-b3e3-b1df6a6f093e)

He revisado la estructura, pero lo veo todo correcto a pesar de no ser así según el error.
![image](https://github.com/user-attachments/assets/8b5c6836-e921-416d-9305-75e08141e638)

Y los datos enviados son.
![image](https://github.com/user-attachments/assets/e9cd007d-a36e-4c84-b34a-dace014fd846)

**Comment by ortegafernando** [comment]
No soy experto pero te diria que antes de enviar, verifiques/valides el xml con los esquemas xsd que hay, de esa forma igual tienes más pistas.
Yo hago esto, por si le sirve a alguien (no soy ningun experto) que me dice más detalle del error:

NOTA: si veis algo confidencial, por favor avisarme para borrarlo
NOTA2: logg y sse_error son funciones "mias" para llevar un log de lo que va ocurriendo, usa tu el sistema que quieras.

A ver si te ayuda en algo, pero te dará más pistas.

Toda esta parte es la que no ví en este repositorio pero buscando en google....

```
                    $errorString = ''; 
                    // Get the validation errors
                    $errors = libxml_get_errors();
                    // Format each error
                    foreach ($errors as $error) {
                        $errorString .= $this->display_xml_error($error, $dom);
                    }
                    logg("ERROR STRING: " . $errorString);
                    // Clear libxml errors
                    libxml_clear_errors(); 
```



```
    public function signTicketBai($data)
    {
        try {
            libxml_use_internal_errors(true);

            $dom = $this->ticket->dom();                                           
            logg('SCHEMA VALIDATE: ' . $dom->schemaValidate($_SESSION['APP_ROOT'] . '/vendor/barnetik/ticketbai/tests/Barnetik/Tbai/__files/specs/ticketbaiv1-2-2-no-signature.xsd'));
            if (!$dom->schemaValidate($_SESSION['APP_ROOT'] . '/vendor/barnetik/ticketbai/tests/Barnetik/Tbai/__files/specs/ticketbaiv1-2-2-no-signature.xsd')) {

                    $errorString = ''; 
                    // Get the validation errors
                    $errors = libxml_get_errors();
                    // Format each error
                    foreach ($errors as $error) {
                        $errorString .= $this->display_xml_error($error, $dom);
                    }
                    logg("ERROR STRING: " . $errorString);
                    // Clear libxml errors
                    libxml_clear_errors(); 
                
                sse_error(array("errors" => [array("message" => "ERROR: ticketBai no valida sobre ticketbaiv1-2-2-no-signature.xsd: " . $errorString)]));
            }
            $signedFilename = '/' . $data['labelType'] . '/signedxmls' . '/' . $data['fiscales']['invoicenumber'] . '-signed.xml';
            $certFile = $this->generalData['certFile'];
            $this->generalData['privateKey'] = \Barnetik\Tbai\PrivateKey::p12($certFile);
            logg('privateKey: ' . $this->generalData['privateKey']->type());
            logg('privateKey: ' . json_encode($this->generalData['privateKey']->certPath()));
            $this->ticket->sign($this->generalData['privateKey'] , $this->generalData['certPassword'], $_SESSION['APP_ROOT'] . $signedFilename);
            logg('despues');
            //Vamos a validar el xml firmado
            $signedDom = new DOMDocument();
            $signedDom->load($_SESSION['APP_ROOT'] . $signedFilename);
            logg('SCHEMA VALIDATE: ' . $signedDom->schemaValidate($_SESSION['APP_ROOT'] . '/vendor/barnetik/ticketbai/tests/Barnetik/Tbai/__files/specs/ticketbaiv1-2-2.xsd'));
            if (!$signedDom->schemaValidate($_SESSION['APP_ROOT'] . '/vendor/barnetik/ticketbai/tests/Barnetik/Tbai/__files/specs/ticketbaiv1-2-2.xsd')) {
                sse_error(array("errors" => [array("message" => "ERROR: ticketBai no valida sobre ticketbaiv1-2-2.xsd")]));
            }  
            return $signedFilename;
        } catch (Throwable $t) {
            $error_message = $t->getMessage() . " at " . $t->getFile() . ":" . $t->getLine() . "\n";
            logg("ERRROR ENCONTRADO:\t" . $error_message);
            sse_error(array("errors" => [array("message" => "Throwable: " . $error_message)]));
        }
```

**Comment by fjsampe** [comment]
Gracias por la respuesta. El error que envía batuz se puede ver con.
     $respuestaComunicacion=$response['respuesta'];
     $content=$respuestaComunicacion->content();
En content vemos los errores indicados.
<SituacionRegistro>
                <EstadoRegistro>Incorrecto</EstadoRegistro>
                <CodigoErrorRegistro>B4_2000070</CodigoErrorRegistro>
                <DescripcionErrorRegistroES>La firma no cumple los requisitos de la política de firma TicketBAI.(EPES: S ALGORITMO: rsa-sha512:2048 POLITICA: N CERTIFICADO_ADMITIDO: S )</DescripcionErrorRegistroES>
                <DescripcionErrorRegistroEU>Sinadurak ez ditu betetzen TicketBAI sinaduraren politikaren baldintzak.(EPES: S ALGORITMO: rsa-sha512:2048 POLITICA: N CERTIFICADO_ADMITIDO: S )</DescripcionErrorRegistroEU>
            </SituacionRegistro>

Esto indica que la política de firma no ha sido correctamente definida. Quisiera saber este punto donde está implementado en la librería para revisar mi código.

**Comment by fjsampe** [comment]
Solucionado. El problema en sí era los identificadores de política. Por no utilizar la libreria XADES de este proyecto debido a utilizar una versión de symfony más antigua utilicé la misma que se utiliza en el proyecto FACE de
[Facturae-PHP](https://github.com/josemmo/Facturae-PHP) para firmar facturas electrónicas para FACE para componer el fichero a enviar.

En esta generación no se incluían estas políticas.
    const POLICY_IDENTIFIER_GIPUZKOA = 'https://www.gipuzkoa.eus/ticketbai/sinadura';
    const POLICY_DIGEST_GIPUZKOA = 'vSe1CH7eAFVkGN0X2Y7Nl9XGUoBnziDA5BGUSsyt8mg=';
    const POLICY_IDENTIFIER_BIZKAIA = 
'https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf';
    const POLICY_DIGEST_BIZKAIA = 'Quzn98x3PMbSHwbUzaj5f5KOpiH0u8bvmwbbbNkO9Es=';
    const POLICY_IDENTIFIER_ARABA = 'https://ticketbai.araba.eus/tbai/sinadura/';
    const POLICY_DIGEST_ARABA = 'd69VEBc4ED4QbwnDtCA2JESgJiw+rwzfutcaSl5gYvM=';

**Comment by arraintxo** [comment]
Gracias por indicar cual era el problema original.

Un saludo,
