### ISSUE TITLE
DUDA SOBRE LA LIBRERIA

### ISSUE THREAD

**Issue by ccalvis96** [Barnetik/tbai-php-lib#44]
Buenas tardes,

Estoy mirando de implementar esta librería en un proyecto de PHP y me gustaría saber cual es el documento maestro para la generación del XML de la factura, para firmar dicha factura, para realizar el envío i gestionar la respuesta y para generar el código qr.

Disculpad mi ignorancia pero no he utilizado muchas librerías descargadas de GitHub y en algunas esta explicado en el documento README.txt.

Muchas gracias de antemano,
Saludos

**Comment by arraintxo** [comment]
Buenas @ccalvis96 ,

Hemos añadido la documentación básica necesaria para hacer funcionar la librería en el README.

Un saludo,
