### ISSUE TITLE
Posible error al cargar un tbai internacional desde xml

### ISSUE THREAD

**Issue by mnlcasal** [Barnetik/tbai-php-lib#47]
Hola,

nos está pasando que al intentar generar un objeto ticketbai desde el xml nos genera las facturas internacionales (en las que el recipiente tiene IDOtro en lugar  de NIF) como si fueran nacionales y con el campo NIF vacío.

cacharreando un poco creo que puede deberse a que este if siempre nos devuelve false porque nos está comparando un float con un entero.

Si alguien más puede comprobarlo, para descartar que sea alguna combinación de nuestra version de php, sistema o extensiones... bastaría con hacer un par de var_dump antes de la siguiente línea :

https://github.com/Barnetik/tbai-php-lib/blob/06f0314e6c0443bfdcec03dbaa08105db730ff54/src/Barnetik/Tbai/Subject/Recipient.php#L111

`var_dump($xpath->evaluate('count(NIF)', $contextNode));`
`var_dump(0);`

Esto a nosotros nos da un float y un int. Entiendo que se hace una comparación con === porque si evaluate da error devuelve false y se puede confundir con el 0.

Muchas gracias por el trabajo!

**Comment by mnlcasal** [comment]
Lo hemos parcheado asi:

```
$countNIF = $xpath->evaluate('count(NIF)', $contextNode);
if (is_numeric($countNIF) && (int)$countNIF === 0) {
```

**Comment by arraintxo** [comment]
Buenas @mnlcasal ,

tal y como dices el evaluate devolvía un float al no encontrar el NIF, he optado por cambiar el orden y no hacer una comprobación del tipado.  Según la documentación de PHP (https://www.php.net/manual/en/domxpath.evaluate.php) este método solo debería devolver false en caso de que la expresión esté mal formada, por lo que no debería darse el caso.

Eskerrik asko,
