### ISSUE TITLE
Problema con facturas de Grecia con NIF EU Intracomunitario

### ISSUE THREAD

**Issue by ortegafernando** [Barnetik/tbai-php-lib#48]
Buenas, la verdad es que es algo "complejo de detectar", pero aquí tenéis también un ejemplo https://github.com/DragonBe/vies/issues/57

Y aquí podéis comprobar el NIF correspondiente:  https://ec.europa.eu/taxation_customs/vies/#/vat-validation
Si seleccionáis GRECIA veréis como Europa considera EL como su código país, aún y cuando el código país ISO es GR

Podeis comprobar como este NIF se verifica correctamente en EUROPA: "EL033862894"

Me he visto obligado a cambiar el código de Recipient.php, en la función "public function xml(DOMDocument $domDocument): DOMNode"

De 

```
            if ($this->hasNifAsVatId() && substr($vatId, 0, 2) !== $this->countryCode()) {
                $vatId = $this->countryCode . $vatId;
            }
```

He cambiado a:
```
            //Caso GRECIA, el countryCode ISO es GR, sin embargo para VIES, el NIF comienza por EL, de no añadir el ultimo bloque del if, se nos forma un vatId tipo GRELXXXXXXXX, que es inválido
            if ($this->hasNifAsVatId() && substr($vatId, 0, 2) !== $this->countryCode() && !(substr($vatId, 0, 2) == 'EL' && $this->countryCode() == 'GR')) {
                $vatId = $this->countryCode . $vatId;
            }
```

Con el código antiguo acaba teniendo en el fichero ticketbai GRELXXXXXXXX y Batuz NO admitía el NIF, diciendo que era erróneo. 

Con la modificación del código, **evito añadir GR delante**, dado que el NIF empezando por EL es perfectamente válido en Grecia, aunque el código ISO pais no coincida con las dos primeras letras del NIF.

Con dicha modificación, he podido crear la factura perfectamente.

Por favor, podéis modificarlo para ayudar al siguiente? Gracias

**Comment by arraintxo** [comment]
Ya está cambiado. Eskerrik asko por el aviso. 

Al parecer son el único pais que usa el código del idioma para el tema del VIES :(
