### ISSUE TITLE
Datos de ejemplo

### ISSUE THREAD

**Issue by daniel89fg** [Barnetik/tbai-php-lib#5]
Hola.

En la documentación solo vemos un ejemplo de una factura. Sería posible que puedan añadir más ejemplos por ejemplos, facturas con varios ivas, con retenciones, suplidos, recargos y un poco todo para ver como se generan los datos correctamente.

Tenemos algunas dudas sobre como generar todos los breakdown posibles correctamente y es por ver ejemplos.

Gracias.

**Comment by arraintxo** [comment]
La verdad es que no tenemos ejemplos generados y no se si podríamos tenerlos en breve.

De todos modos, échale un vistazo a este documento de la diputación de Gipuzkoa que he subido al directorio de docs, puede que te aclare algo más como funcionaría cada uno de los campos:
https://github.com/Barnetik/tbai-php-lib/blob/main/docs/TicketBai%20-%20Estructura%20y%20validaciones.pdf 

Es la estructura en la que se basa el fichero de ticketbai. En nuestro caso hemos "aplanado" alguna de las estructuras (especialmente en el desglose o breakdown) para no tener que generar árboles tan complejos.

**Comment by daniel89fg** [comment]
Vale, gracias le echamos un ojo ;)
