### ISSUE TITLE
El interesado no está identificado (N3_0000002)

### ISSUE THREAD

**Issue by goear** [Barnetik/tbai-php-lib#6]
Aupa @arraintxo, lo primero agradecerte el trabajazo que os estáis pegando en Barnetik.

Creo que estoy haciendo algo mal, pero no se el que, estoy recibiendo esta respuesta:
![Screenshot from 2022-03-30 12-32-06](https://user-images.githubusercontent.com/29330729/160812045-07b82148-51bf-473c-ab65-bfe96d35ffdd.png)

En el fichero .env tengo lo siguiente:
### ticketbai values for testing ###
TBAI_ISSUER_NIF="00000000T"
TBAI_ISSUER_NAME="Issuer name"
TBAI_APP_LICENSE="TBAIBI00000000PRUEBA"
TBAI_APP_DEVELOPER_NIF="11111111H"
TBAI_APP_NAME="SOFTWARE GARANTE TICKETBAI PRUEBA"
TBAI_APP_VERSION="1.0"

y aquí el código:

`
$nif = $_ENV['TBAI_ISSUER_NIF'];
        $issuer = $_ENV['TBAI_ISSUER_NAME'];
        $license = $_ENV['TBAI_APP_LICENSE'];
        $developer = $_ENV['TBAI_APP_DEVELOPER_NIF'];
        $appName = $_ENV['TBAI_APP_NAME'];
        $appVersion =  $_ENV['TBAI_APP_VERSION'];

        $subject = $this->getForeignSubject($nif, $issuer);
        $fingerprint = $this->getFingerprint($license, $developer, $appName, $appVersion);

        $header = Header::create((string)time(), new Date(date('d-m-Y')), new Time(date('H:i:s')), $this->testSerie());
        sleep(1); // Avoid same invoice number as time is used for generation
        $data = new Data('factura ejemplo TBAI', new Amount('89.36'), [Data::VAT_REGIME_01]);
        $data->addDetail(new Detail('Artículo 1 Ejemplo', new Amount('23.356', 12, 8), new Amount('1'), new Amount('25.84'), new Amount('2.00')));
        $data->addDetail(new Detail('Artículo 2 xxx', new Amount('18.2', 12, 8), new Amount('1.50'), new Amount('33.03')));
        $data->addDetail(new Detail('Artículo 3 aaaaaaa', new Amount('1.40', 12, 8), new Amount('18'), new Amount('30.49')));

        $breakdown = new Breakdown();

        $vatDetail = new VatDetail(new Amount('73.86'), new Amount('21'), new Amount('15.50'));

        $foreignServiceSubjectNotExemptBreakdown = new ForeignServiceSubjectNotExemptBreakdownItem(ForeignServiceSubjectNotExemptBreakdownItem::NOT_EXEMPT_TYPE_S1, [$vatDetail]);
        $breakdown->addForeignServiceSubjectNotExemptBreakdownItem($foreignServiceSubjectNotExemptBreakdown);
        $selfEmployed = false;
        $territory = TicketBai::TERRITORY_BIZKAIA;

        $invoice = new Invoice($header, $data, $breakdown);
        $tbai = new TicketBai(
            $subject,
            $invoice,
            $fingerprint,
            $territory,
            $selfEmployed
        );

        $signedFilename = tempnam(__DIR__ , 'signed-');
        rename($signedFilename, $signedFilename . '.xml');
        $signedFilename = $signedFilename . '.xml';

        $certFile = 'PertsonaFisikoa_PersonaFisica.p12';

        $crtf = file_get_contents($certFile);
        $certPassword = 'IZDesa2021';

        $privateKey = PrivateKey::p12($certFile);

        $tbai->sign($privateKey, $certPassword, $signedFilename);

        $endpoint = new Endpoint(true, true); //using Barnetik\Tbai\Api\Bizkaia\Endpoint for Bizkaia

        $response = $endpoint->submitInvoice($tbai,$privateKey,$certPassword);

        dump($response);`

Mila esker zure laguntzagatik.

**Comment by arraintxo** [comment]
Egun on @goear ,

tienes que solicitar a cada una de las diputaciones contra la que vayas a hacer pruebas un usuario / licencia para la aplicación que estés desarrollando. 

Hay que enviarles un correo con los datos necesarios a:

- Araba: [informaciontecnicaTBAI@araba.eus](mailto:informaciontecnicaTBAI@araba.eus)
- Bizkaia: [batuz.entornodepruebas@bizkaia.eus](mailto:batuz.entornodepruebas@bizkaia.eus)
- Gipuzkoa: [ticketbaikontsultak@gipuzkoa.eus](mailto:ticketbaikontsultak@gipuzkoa.eus)

Y facilitarles los siguientes datos:

- Nombre de la empresa desarrolladora
- NIF de la empresa desarrolladora
- Nombre del "software garante"
- Persona de contacto
  - Nombre
  - Email
  - Teléfono

**Comment by arraintxo** [comment]
Kaixo berriz @goear,

cada entidad desarrolladora tiene que pedir un certificado válido para las pruebas. No es necesario registrar el software en este estadio, pero sí tener un código identificativo para el realizar las pruebas.

Basta con enviar un correo a las direcciones que indico en el mensaje anterior, no van a pedir nada más.

Ondo izan,
